apiVersion: v1
kind: Service
metadata:
  labels:
    name: erank-app
  name: erank-app-svc
  namespace: erank
spec:
  type: LoadBalancer
  selector:
    app: erank-app
  ports:
  - name: http
    protocol: TCP
    port: 3000
    #nodePort: 30001
    targetPort: 3000
